### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by Light7774** [phamquiduong/facemark_detector#1]
Traceback (most recent call last):
  File "C:\Users\Nice\facemark_detector\detector.py", line 13, in <module>
    rec=cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2' has no attribute 'face'

**Comment by phamquiduong** [comment]
You must install [opencv-contrib-python](https://pypi.org/project/opencv-contrib-python/)
`pip install opencv-contrib-python`
This library may not be installed successfully

**Comment by Light7774** [comment]
thanks! I'll do it
